AHC_DEV_05/AHC_DEV_05/Controllers/User/OrderController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using AHCBL.Dto;
using AHCBL.Dto.Admin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class OrderController : Controller
    {
        Permission checkuser = new Permission();

        //[HttpGet]
        public ActionResult Index(string token, string status, int? page)
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
                                                                                   //var data = ProductDao.Instance.GetProductOrder(1);
                                                                                        //var data = OrderDao.Instance.GetProductOrder(1);
            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            ViewBag.rows = rows;

            int id = 0;
            if (token != null)
            {
                id = Util.NVLInt(DataCryptography.Decrypt(token));
            }
            var data = OrderDao.Instance.GetProductOrder(id, status);
            return View(data);

            //return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(rows)));
            //var data = OrderDao.Instance.GetProductOrder(1).Find(smodel => smodel.id == id);
            //    return View(data);
            //return View(data);
        }
        public ActionResult Sell_list()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
            //var data = ProductDao.Instance.GetProductOrder(2);
            var data = OrderDao.Instance.GetProductSaleOrder(0, "", "sale");
            return View(data);
        }
        public ActionResult Order_have()
        {
            checkuser.chkrights("user");
            var data = OrderDao.Instance.GetProductOrder(0, "");
            return View(data);
        }
        public ActionResult Order_buy_point()
        {
            checkuser.chkrights("user");
            ViewBag.bank_info = Varible.Config.bank_info;
            //var bank = DropdownDao.Instance.GetDataBank().Find(smodel => smodel.id == Varible.User.member_id);
            ViewBag.product_amt = Varible.Config.jewel_price.Replace(".00", "");// ConfigurationManager.AppSettings["product_amt"];
            ViewBag.exchange = Varible.Config.exchange.Replace(".00", ""); //Util.NVLDecimal(Varible.Config.exchange).ToString("0,0", CultureInfo.InvariantCulture);
            ViewBag.bank_info = Varible.Config.bank_info;// ConfigurationManager.AppSettings["bank_info"];
            int amt = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            //ViewBag.amount = amt < 1000 ? amt.ToString() : amt.ToString("0,0", CultureInfo.InvariantCulture); //Varible.User.amount;
            ViewBag.amount = amt;
            ViewBag.product_qty = DropdownDao.Instance.GetDataPoint();
            ViewBag.txt1 = Varible.Config.txt1;
            ViewBag.bank_acc = Varible.Config.bank_acc; 

            return View();

        }

        public ActionResult BuyChip(string buy_name, int point, int amount, int price, int pay_type)
        {
            try
            {
                string wait = ConfigurationManager.AppSettings["wait"];
                PointListDto model = new PointListDto();
                model.username = buy_name;
                model.name = wait;
                model.pay_type = pay_type;
                model.amount = Util.NVLString(amount);
                model.price = Util.NVLString(price);
                model.total = Util.NVLString((point + amount));
                string result = PointListDao.Instance.SaveDataList(model, "mony");
                if (result != "OK")
                {
                    return Json(result);
                }
                else
                {
                    return Json("Successfully !");
                }

            }
            catch (Exception e)
            {
                return Json("Error !!");
            }
        }
        public ActionResult Order_send_point()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            return View();
        }
        public ActionResult TranPoint(int point, string pass)
        {
            try
            {
                if (pass != Varible.User.pass)
                {
                    return Json(new returnsave { err = "1", errmsg = "비밀번호가 일치하지 않습니다." });
                }
                else
                {
                    int p_id = Util.NVLInt(Session["member_id"]);
                    string result = PointListDao.Instance.TranPoint(0, point, p_id, "");
                    if (result != "OK")
                    {
                        return Json(new returnsave { err = "1", errmsg = "Error" });
                    }
                    else
                    {
                        return Json(new returnsave { err = "0", errmsg = "꿀벌 전송이 완료되었습니다." });
                    }
                }
            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "1", errmsg = "Error" });
            }
        }
        public ActionResult ChkUserID(string pUid)
        {
            try
            {

                int member_id = 0;
                string pUName = string.Empty;
                int member_level = 0;
                string password = string.Empty;
                string amount = string.Empty;
                Session.Remove("member_id");
                bool result = LoginDao.Instance.ChkAuthDB(pUid, ref member_id, ref pUName, ref member_level, ref password, ref amount);
                if (result == false)
                {
                    return Json(new returnsave { err = "1", errmsg = "회원을 찾을수 없습니다." });
                }
                else
                {
                    Session["member_id"] = member_id;
                    return Json(new returnsave { err = "0", errmsg = "아이디가 확인되었습니다.\n꿀벌 전송을 진행해주세요." });
                }
            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "0", errmsg = "Error" });
            }


            //return objreturnsave;
        }
        public ActionResult Order_list_point(int? page)
        {
            checkuser.chkrights("user");
            /*
            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            var data = ProductDao.Instance.GetOrderList();
            var buy = OrderDao.Instance.GetBuy();
            ViewBag.buy = buy;
            var sale = OrderDao.Instance.GetSale();
            ViewBag.sale = sale;

            return View(data.ToList().ToPagedList(page ?? 1, rows));
            */
            ViewBag.add = OrderDao.Instance.GetAdd();
            ViewBag.buy = OrderDao.Instance.GetBuy();
            ViewBag.sale = OrderDao.Instance.GetSale();
            ViewBag.Withdraw = OrderDao.Instance.GetWithdraw();
            ViewBag.Interest = OrderDao.Instance.GetInterest();
            ViewBag.Benefit = OrderDao.Instance.GetBenefit();
            //ViewBag.Interest = OrderDao.Instance.GetInterest();
            return View();
        }
        public ActionResult Sell_apply(string Token)
        {
            checkuser.chkrights("user");
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(Token));
                var data = OrderDao.Instance.GetProductAppv(id);
                if (data.tab2.Count != 0)
                {
                    return View(data);
                }
                else
                {
                    ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
                                                                                                //var data = ProductDao.Instance.GetProductOrder(2);
                    data = OrderDao.Instance.GetProductOrder(0, "");
                    return View("~/Views/Order/Sell_list.cshtml", data);
                    //return View(data);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Order_apply(string Token)
        {
            checkuser.chkrights("user");
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(Token));
                var data = OrderDao.Instance.GetProductSale(id);
                if (data.tab2.Count == 0)
                {
                    return RedirectToAction("Matching");
                }
                return View(data);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Matching()
        {
            return View();

        }
        public ActionResult Appv(int orderId, string buy_info, string token)
        {
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(token));
                string result = OrderDao.Instance.SaveData(orderId, id, buy_info, buy_info == "" ? "apv" : "buy");
                string chk = buy_info == "" ? "apv" : "";
                if (result != "OK")
                {
                    return Json(new returnsave { err = "1", errmsg = "Error" });
                }
                else
                {
                    if (chk == "apv")
                    {
                        var data = OrderDao.Instance.GetUserdata(orderId);
                        int cnt = 0;

AHC_DEV_05/AHC_DEV_05/Controllers/User/WithdrawTransController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_DEV_05.Controllers.User
{
    public class WithdrawTransController : Controller
    {
        // GET: WithdrawTrans
        public ActionResult Index()
        {
            return View();
        }
    }
}

AHC_DEV_05/AHC_DEV_05/Views/WithdrawTrans/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_table.cshtml";
}
<div class="width1100" style="margin-top:15px;" data-aos="fade-up" data-aos-duration="2000">
    <p class="pTit" id="t_page_title">내역</p>
    <div class="tabWrap">
        <ul>
            <li class="tab02"><a href="@Url.Action("Order_list_point","Order")"><span style="color:#000;">충전내역</span></a></li>
            <li class="tab02"><a href="@Url.Action("Index","BuyListTrans")" class="tran02"><span style="color:#000;">구매내역</span></a></li>
            <li class="tab02"><a href="@Url.Action("Sell_history","BuyListTrans")"><span style="color:#000;">판매내역</span></a></li>
            <li class="tab02 on"><a href="@Url.Action("Index","WithdrawTrans")"><span style="color:#000;">출금(원금)내역</span></a></li>
            <li class="tab02"><a><span style="color:#000;">출금(이자)내역</span></a></li>
        </ul>
    </div>
    <div id="main">
        <div class="member-inform" data-aos="fade-up" data-aos-duration="2000">
            <div class="tab_con" id="tab-con">
                <div id="member" class="tab-content page-inner-03">
                    <div class="member-inform-box01 inform-box">
                        <div class="inform-top">
                            <h4 style="margin:10px 0; color:#000; text-align:center;">출금(원금)내역</h4>
                        </div>

                        <div class="choice-effect">
                            <table style="width:100%;border-collapse:collapse;text-align:center; color:#fff;">
                                <tr>
                                    <th>No</th>
                                    <th>날짜</th>
                                    <th>금액</th>
                                    <th>수수료</th>
                                    <th>합계</th>
                                    <th>비고</th>
                                </tr>
                                <tr>
                                    <td>xxx</td>
                                    <td>xxx</td>
                                    <td>xxx</td>
                                    <td>xxx</td>
                                    <td>xxx</td>
                                    <td>xxx</td>
                                </tr>
                                <tr class="text-center">
                                    <td colspan="7">
                                        No Data !!
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>