AHC_DEV_05/AHC_DEV_05/Controllers/User/MainController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using AHCBL.Dto;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class MainController : Controller
    {
        Permission checkuser = new Permission();
        // GET: main
        public ActionResult Index()
        {
            checkuser.chkrights("user");
            var data = MainDao.Instance.GetDataList();
            decimal amt = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            decimal amt_interest = GetDataDao.Instance.GetPointInterest(Varible.User.member_id);
            //decimal amt_withdrawal = GetDataDao.Instance.GetPointWithdrawal(Varible.User.member_id);

            ViewBag.point = Util.NVLInt(amt);
            ViewBag.amount = Util.NVLInt(amt) <1000 ? Util.NVLInt(amt).ToString() : amt.ToString("0,0", CultureInfo.InvariantCulture);
            ViewBag.interest = Util.NVLInt(amt_interest) < 1000 ? Util.NVLInt(amt_interest).ToString() : amt_interest.ToString("0,0", CultureInfo.InvariantCulture);
            ViewBag.withdrawal = Util.NVLInt(amt_interest) < 1000 ? Util.NVLInt(amt_interest).ToString() : amt_interest.ToString("0,0", CultureInfo.InvariantCulture);//Util.NVLInt(amt_withdrawal) < 1000 ? Util.NVLInt(amt_withdrawal).ToString() : amt_withdrawal.ToString("0,0", CultureInfo.InvariantCulture);
            ViewBag.persen = Util.NVLInt(Varible.Config.point_percent1);
            return View(data);
        }
        public ActionResult Savedata(string fee, string amt, string total, string interest)
        {
            try
            {
                int id = 0;
                string result = MainDao.Instance.SaveDataList(id, fee, amt, total, interest,"add");

                if (result == "OK")
                {
                    return Json(new returnsave { err = "0", errmsg = "성공하셨습니다 !" });
                }
                else
                {
                    return Json(new returnsave { err = "1", errmsg = "에러." });
                }
            }
            catch 
            {
                return Json(new returnsave { err = "1", errmsg = "에러." });
            }

        }
    }
}

AHC_DEV_05/AHC_DEV_05/Controllers/User/MemberController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using AHCBL.Dto;
using AHCBL.Dto.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class MemberController : Controller
    {
        Permission checkuser = new Permission();
        // GET: Member
        public ActionResult Index()
        {
            if (ModelState.IsValid)
            {
                checkuser.chkrights("user");
                //ViewBag.Bank = DropdownDao.Instance.GetDataBank();
                ViewBag.OldPass = Varible.User.pass;
                var model = MemberListDao.Instance.GetDataList().Find(smodel => smodel.id == Varible.User.member_id);
                var bank_id = DropdownDao.Instance.GetDataBank();
                model.bank_list = new SelectList(bank_id, "Value", "Text");


                return View(model);
            } 
            else
            {
                return View();
            }
                
        }
        public ActionResult ChangeBank(int id,int bank_id,string acc_no,string acc_name)
        {
            try
            {

                MemberListDto model = new MemberListDto();
                model.id = id;
                model.bank_id = bank_id;
                model.acc_no = acc_no;
                model.acc_name = acc_name;

                string result = MemberDao.Instance.ChangeBank(model);
                if (result != "OK")
                {
                    //ViewBag.Message = result;
                    return Json(new returnsave { err = "1", errmsg = result });
                }
                else
                {
                    //return RedirectToAction("Member");
                    return Json(new returnsave { err = "0", errmsg = "성공하셨습니다 !" });
                }

            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "0", errmsg = "에러" });
            }


            //return objreturnsave;
        }
        //[HttpPost]
        //public ActionResult ChangeBank(MemberListDto model)
        //{
        //    try
        //    {

        //        string result = MemberDao.Instance.ChangeBank(model);
        //        if (result != "OK")
        //        {
        //            ViewBag.Message = result;
        //        }
        //        else
        //        {
        //            //return RedirectToAction("Member");
        //            return View("Member");
        //        }
        //        return View();


        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}



        public ActionResult ChangePass(int id ,string pass)
        {
            try
            {
                MemberDao.Instance.ChangePass(id,pass);
                return Json("성공하셨습니다 !");
            }
            catch (Exception e)
            {
                return Json("에러");
            }
        }


        //[HttpPost]
        //public ActionResult ChangePass(MemberListDto model)
        //{
        //    try
        //    {
        //        if (Varible.User.pass != model.password)
        //        {
        //            return Json(new { status = "Error", message = "Password incorrect !" });
        //        }
        //        //string result = MemberDao.Instance.ChangeBank(model);
        //        //if (result != "OK")
        //        //{
        //        //    ViewBag.Message = result;
        //        //}
        //        //else
        //        //{
        //        //    return RedirectToAction("Index");
        //        //}
        //        return View();
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

    }
}

AHC_DEV_05/AHC_DEV_05/Controllers/User/OrderController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using AHCBL.Dto;
using AHCBL.Dto.Admin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class OrderController : Controller
    {
        Permission checkuser = new Permission();

        //[HttpGet]
        public ActionResult Index(string token, string status, int? page)
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
                                                                                   //var data = ProductDao.Instance.GetProductOrder(1);
                                                                                        //var data = OrderDao.Instance.GetProductOrder(1);
            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            ViewBag.rows = rows;

            int id = 0;
            if (token != null)
            {
                id = Util.NVLInt(DataCryptography.Decrypt(token));
            }
            var data = OrderDao.Instance.GetProductOrder(id, status);
            return View(data);

            //return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(rows)));
            //var data = OrderDao.Instance.GetProductOrder(1).Find(smodel => smodel.id == id);
            //    return View(data);
            //return View(data);
        }
        public ActionResult Sell_list()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
            //var data = ProductDao.Instance.GetProductOrder(2);
            var data = OrderDao.Instance.GetProductSaleOrder(0, "", "sale");
            return View(data);
        }
        public ActionResult Order_have()
        {
            checkuser.chkrights("user");
            var data = OrderDao.Instance.GetProductOrder(0, "");
            return View(data);
        }
        public ActionResult Order_buy_point()
        {
            checkuser.chkrights("user");
            ViewBag.bank_info = Varible.Config.bank_info;
            //var bank = DropdownDao.Instance.GetDataBank().Find(smodel => smodel.id == Varible.User.member_id);
            ViewBag.product_amt = Varible.Config.jewel_price.Replace(".00", "");// ConfigurationManager.AppSettings["product_amt"];
            ViewBag.exchange = Varible.Config.exchange.Replace(".00", ""); //Util.NVLDecimal(Varible.Config.exchange).ToString("0,0", CultureInfo.InvariantCulture);
            ViewBag.bank_info = Varible.Config.bank_info;// ConfigurationManager.AppSettings["bank_info"];
            int amt = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            //ViewBag.amount = amt < 1000 ? amt.ToString() : amt.ToString("0,0", CultureInfo.InvariantCulture); //Varible.User.amount;
            ViewBag.amount = amt;
            ViewBag.product_qty = DropdownDao.Instance.GetDataPoint();
            ViewBag.txt1 = Varible.Config.txt1;
            ViewBag.bank_acc = Varible.Config.bank_acc; 

            return View();

        }

        public ActionResult BuyChip(string buy_name, int point, int amount, int price, int pay_type)
        {
            try
            {
                string wait = ConfigurationManager.AppSettings["wait"];
                PointListDto model = new PointListDto();
                model.username = buy_name;
                model.name = wait;
                model.pay_type = pay_type;
                model.amount = Util.NVLString(amount);
                model.price = Util.NVLString(price);
                model.total = Util.NVLString((point + amount));
                string result = PointListDao.Instance.SaveDataList(model, "mony");
                if (result != "OK")
                {
                    return Json(result);
                }
                else
                {
                    return Json("Successfully !");
                }

            }
            catch (Exception e)
            {
                return Json("Error !!");
            }
        }
        public ActionResult Order_send_point()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            return View();
        }
        public ActionResult TranPoint(int point, string pass)
        {
            try
            {
                if (pass != Varible.User.pass)
                {
                    return Json(new returnsave { err = "1", errmsg = "비밀번호가 일치하지 않습니다." });
                }
                else
                {
                    int p_id = Util.NVLInt(Session["member_id"]);
                    string result = PointListDao.Instance.TranPoint(0, point, p_id, "");
                    if (result != "OK")
                    {
                        return Json(new returnsave { err = "1", errmsg = "Error" });
                    }
                    else
                    {
                        return Json(new returnsave { err = "0", errmsg = "꿀벌 전송이 완료되었습니다." });
                    }
                }
            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "1", errmsg = "Error" });
            }
        }
        public ActionResult ChkUserID(string pUid)
        {
            try
            {

                int member_id = 0;
                string pUName = string.Empty;
                int member_level = 0;
                string password = string.Empty;
                string amount = string.Empty;
                Session.Remove("member_id");
                bool result = LoginDao.Instance.ChkAuthDB(pUid, ref member_id, ref pUName, ref member_level, ref password, ref amount);
                if (result == false)
                {
                    return Json(new returnsave { err = "1", errmsg = "회원을 찾을수 없습니다." });
                }
                else
                {
                    Session["member_id"] = member_id;
                    return Json(new returnsave { err = "0", errmsg = "아이디가 확인되었습니다.\n꿀벌 전송을 진행해주세요." });
                }
            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "0", errmsg = "Error" });
            }


            //return objreturnsave;
        }
        public ActionResult Order_list_point(int? page)
        {
            checkuser.chkrights("user");
            /*
            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            var data = ProductDao.Instance.GetOrderList();
            var buy = OrderDao.Instance.GetBuy();
            ViewBag.buy = buy;
            var sale = OrderDao.Instance.GetSale();
            ViewBag.sale = sale;

            return View(data.ToList().ToPagedList(page ?? 1, rows));
            */
            ViewBag.add = OrderDao.Instance.GetAdd();
            ViewBag.buy = OrderDao.Instance.GetBuy();
            ViewBag.sale = OrderDao.Instance.GetSale();
            ViewBag.Withdraw = OrderDao.Instance.GetWithdraw();
            ViewBag.Interest = OrderDao.Instance.GetInterest();
            ViewBag.Benefit = OrderDao.Instance.GetBenefit();
            //ViewBag.Interest = OrderDao.Instance.GetInterest();
            return View();
        }
        public ActionResult Sell_apply(string Token)
        {
            checkuser.chkrights("user");
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(Token));
                var data = OrderDao.Instance.GetProductAppv(id);
                if (data.tab2.Count != 0)
                {
                    return View(data);
                }
                else
                {
                    ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
                                                                                                //var data = ProductDao.Instance.GetProductOrder(2);
                    data = OrderDao.Instance.GetProductOrder(0, "");
                    return View("~/Views/Order/Sell_list.cshtml", data);
                    //return View(data);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Order_apply(string Token)
        {
            checkuser.chkrights("user");
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(Token));
                var data = OrderDao.Instance.GetProductSale(id);
                if (data.tab2.Count == 0)
                {
                    return RedirectToAction("Matching");
                }
                return View(data);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Matching()
        {
            return View();

        }
        public ActionResult Appv(int orderId, string buy_info, string token)
        {
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(token));
                string result = OrderDao.Instance.SaveData(orderId, id, buy_info, buy_info == "" ? "apv" : "buy");
                string chk = buy_info == "" ? "apv" : "";
                if (result != "OK")
                {
                    return Json(new returnsave { err = "1", errmsg = "Error" });
                }
                else
                {
                    if (chk == "apv")
                    {
                        var data = OrderDao.Instance.GetUserdata(orderId);
                        int cnt = 0;

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_Error.cshtml
<!DOCTYPE html>
<html>
<head>
    @*<meta charset="utf-8" />*@
    <meta http-equiv=Content-Type content="text/html; charset=tis-620">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 장미나라</title>
    <link rel="icon" href="/vendor/images/logo.ico" type="image/x-icon" sizes="16x16">
    @Styles.Render("~/Content/css")
</head>
<body class="xp-vertical">

    <div class="xp-authenticate-bg"></div>
    <!-- Start XP Container -->
    <div id="xp-container" class="xp-container">
        @RenderBody()
    </div>
    <!-- End XP Container -->
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_Main.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>승리호</title>
    <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
    <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' />
    @Styles.Render("~/common/css/pages/style.css")
    @Styles.Render("~/common/css/main.css")
    @Styles.Render("~/common/css/pages/slide-nav.css")
    @Scripts.Render("~/common/script/jquery-3.4.1.min.js")
</head>
<body style="display:flex; justify-content:center; background: #000;">
    <div id="wrap">
        <div class="container" style="position:relative;">
            <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                @*<a class="menu-nav" href="@Url.Action("","Main")">
                    <img class="img-menu" src="~/common/image/icon1-01.png" />
                    <span>홈</span>
                </a>*@
                <a class="menu-nav" href="@Url.Action("Product_buy_list", "Order")">
                    <img  class="img-menu" src="~/common/image/icon1.png" />
                    <span>현재구매중</span>
                </a>
                <a class="menu-nav" href="@Url.Action("order_buy_point","Order")">
                    <img class="img-menu" src="~/common/image/icon2.png" />
                    <span>신청하기</span>
                </a>
                @*<a class="menu-nav" href="@Url.Action("Index","Notice")">
                    <img class="img-menu" src="~/common/image/icon3-01.png" />
                    <span>게시판</span>
                </a>*@
                <a class="menu-nav" href="@Url.Action("Order_list_point", "Order")">
                    <img class="img-menu" src="~/common/image/icon3.png" />
                    <span>내역</span>
                </a>
                <a class="menu-nav" href="@Url.Action("Index","ChartMember")">
                    <img class="img-menu" src="~/common/image/icon4.png" />
                    <span>조직도</span>
                </a>
                <a class="menu-nav" href="@Url.Action("Index","Member")">
                    <img class="img-menu" src="~/common/image/icon5.png" />
                    <span>내정보</span>
                </a>
                <a class="menu-nav" href="https://open.kakao.com/o/sQmiZ1Xc">
                    <img class="img-menu" src="~/common/image/icon6.png" />
                    <span> 1:1 문의</span>
                </a>
                <a class="menu-nav" href="https://open.kakao.com/o/gls89bYc">
                    <img class="img-menu" src="~/common/image/icon6.png" />
                    <span>카톡정보방</span>
                </a>
                <a class="menu-nav" href="~/Login/LogOut">
                    <i style="font-size:35px; color:#ff9800" class="fas fa-sign-out-alt"></i>
                    <span>로그아웃</span>
                </a>
            </div>
            <div class="dash-bonus" style="margin-bottom:0">
                <span style="font-size:50px;cursor:pointer; color:#ff0606" onclick="openNav()">&#9776;</span>
                <div class="gnp">
                    <a href="@Url.Action("","Main")">
                        <span style="font-weight:bold; cursor:pointer; margin-right:10px; color:#fff;">홈</span>
                    </a>
                </div>
                <div class="">
                    <span style=" font-weight: bold; cursor: pointer; font-size:16px; color: #fff;margin-right: 10px;">@Session["username"]</span>
                </div>
                <div class="gnp">
                    <span class="copy">
                        <span style="font-weight:bold; cursor:pointer;  margin-right:10px;">추천링크</span>
                    </span>
                </div>
            </div>

            @RenderBody()
        </div>
    </div>

    <input type="text" value="@Session["url"]" class="urlJoin" style="position:absolute;left:-1000px;top:-1000px;" />

    <script type="text/javascript">
        document.querySelector(".copy").addEventListener("click", copyText);
        function copyText() {
            var copyText = document.querySelector(".urlJoin");
            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");
            alert("복사 된 텍스트 : " + copyText.value);
        }

        function openNav() {
            document.getElementById("mySidenav").style.width = "100px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }

        document.querySelector(".bankAcc").addEventListener("click", copyBank);
        function copyBank() {
            var copyBank = document.querySelector(".bankAcc");
            copyBank.select();
            copyBank.setSelectionRange(0, 99999);
            document.execCommand("copy");
            alert("복사 된 텍스트 : " + copyBank.value);
        }


        function alertRes() {
            alert("계속 될");
        }
    </script>

    @Scripts.Render("~/common/script/Chart.min.js")
    @Scripts.Render("~/common/script/all.js")
    @Scripts.Render("~/common/script/jquery.custom.extend.js")
    @Scripts.Render("~/common/script/commonutil.js")
    @Scripts.Render("~/common/script/jquery.cookie.js")
    @Scripts.Render("~/common/script/clipboard.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_Main_Matching.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyOffice</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    @Styles.Render("~/common/css/pages/style.css")
    @Styles.Render("~/common/css/main.css")
    @Scripts.Render("~/common/script/jquery-3.4.1.min.js")
</head>
<body style="background-image: url('../../common/image/bg-page.png');background-size: cover;">
    <div>
        <div class="container">

            @RenderBody()
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_chart.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>MyOffice</title>

    <script src="~/vendor/chart/js/jquery.min.js"></script>
        <script src="~/vendor/chart/js/loader.js"></script>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        #chart {
            width: 900px;
            height: 500px;
        }


        #chart img {
            height: 90px;
            width: 90px;
        }
        .drop-level{
            padding: 7px;
            border-radius: 5px;
            border: none;
            color: #000;
            background: #f7da04;
        }
    </style>
</head>
<body style="background-image: url('../../common/image/bg-page.png');background-size: cover;margin: 0;">
    <header style="position: relative; top: 0; width: 100%; background: #0e0e0e; padding: 0px; margin: 0px; height:40px;">
    </header>
    @RenderBody()


</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_table.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>승리호</title>
    <script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>
    <script type="text/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js'></script>
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css' />
    @Styles.Render("~/common/css/pages/style.css")
    @Styles.Render("~/common/css/main.css")
    @Styles.Render("~/common/css/table.css")
    @Styles.Render("~/common/css/app.css")

    @Styles.Render("~/common/css/pages/slide-nav.css")
    @Scripts.Render("~/common/script/jquery-3.4.1.min.js")
</head>
<body style="display:flex; justify-content:center; background: #000;">
    <div id="wrap" >
        <div class="container" style="position:relative;">
            <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                @*<a class="menu-nav" href="@Url.Action("","Main")">
                <img class="img-menu" src="~/common/image/icon1-01.png" />
                <span>홈</span>
            </a>*@
                <a class="menu-nav" href="@Url.Action("Product_buy_list", "Order")">
                    <img class="img-menu" src="~/common/image/icon1.png" />
                    <span>현재구매중</span>
                </a>
                <a class="menu-nav" href="@Url.Action("order_buy_point","Order")">
                    <img class="img-menu" src="~/common/image/icon2.png" />
                    <span>신청하기</span>
                </a>
                @*<a class="menu-nav" href="@Url.Action("Index","Notice")">
                <img class="img-menu" src="~/common/image/icon3-01.png" />
                <span>게시판</span>
            </a>*@
                <a class="menu-nav" href="@Url.Action("Order_list_point", "Order")">
                    <img class="img-menu" src="~/common/image/icon3.png" />
                    <span>내역</span>
                </a>
                <a class="menu-nav" href="@Url.Action("Index","ChartMember")">
                    <img class="img-menu" src="~/common/image/icon4.png" />
                    <span>조직도</span>
                </a>
                <a class="menu-nav" href="@Url.Action("Index","Member")">
                    <img class="img-menu" src="~/common/image/icon5.png" />
                    <span>내정보</span>
                </a>
                <a class="menu-nav" href="https://open.kakao.com/o/sQmiZ1Xc">
                    <img class="img-menu" src="~/common/image/icon6.png" />
                    <span> 1:1 문의</span>
                </a>
                <a class="menu-nav" href="https://open.kakao.com/o/gls89bYc">
                    <img class="img-menu" src="~/common/image/icon6.png" />
                    <span>카톡정보방</span>
                </a>
                <a class="menu-nav" href="~/Login/LogOut">
                    <i style="font-size:35px; color:#ff9800" class="fas fa-sign-out-alt"></i>
                    <span>로그아웃</span>
                </a>
            </div>
            <div class="dash-bonus" style="margin-bottom:0">
                <span style="font-size:30px;cursor:pointer; color:#fff;" onclick="openNav()">&#9776;</span>
                <div class="gnp">
                    <a href="@Url.Action("","Main")">
                        <span style="font-weight:bold; cursor:pointer; margin-right:10px; color:#fff;">홈</span>
                    </a>
                </div>
                <div class="gnp">
                    <span style="font-weight:bold; cursor:pointer; margin-right:10px;">@Session["username"]</span>
                </div>
                <div class="gnp">
                    <span class="copy">
                        <span style="font-weight:bold; cursor:pointer; margin-right:10px;">추천링크</span>
                    </span>
                </div>
            </div>

            @RenderBody()
        </div>
    </div>

    <input type="text" value="@Session["url"]" class="urlJoin" style="position:absolute;left:-1000px;top:-1000px;" />

    <script type="text/javascript">
        document.querySelector(".copy").addEventListener("click", copyText);
        function copyText() {
            var copyText = document.querySelector(".urlJoin");
            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");
            alert("복사 된 텍스트 : " + copyText.value);
        }

        function openNav() {
            document.getElementById("mySidenav").style.width = "100px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }

        document.querySelector(".bankAcc").addEventListener("click", copyBank);
        function copyBank() {
            var copyBank = document.querySelector(".bankAcc");
            copyBank.select();
            copyBank.setSelectionRange(0, 99999);
            document.execCommand("copy");
            alert("복사 된 텍스트 : " + copyBank.value);
        }
    </script>

    @Scripts.Render("~/common/script/Chart.min.js")
    @Scripts.Render("~/common/script/all.js")
    @Scripts.Render("~/common/script/jquery.custom.extend.js")
    @Scripts.Render("~/common/script/commonutil.js")
    @Scripts.Render("~/common/script/jquery.cookie.js")
    @Scripts.Render("~/common/script/clipboard.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>