AHC_DEV_05/AHC_DEV_05/Controllers/Admin/SellHistoryController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dto.Admin;
using OfficeOpenXml;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.Admin
{
    public class SellHistoryController : Controller
    {
        Permission checkuser = new Permission();
        // GET: RequestList

        // GET: SellHistory
        public ActionResult Index(int? page, string drp, string keyword)
        {
            checkuser.chkrights("admin");
            var data = RequestListDao.Instance.GetSellList();
            int rows = Util.NVLInt(Varible.Config.page_rows);
            var count = data.Count;

            TempData["data"] = data.ToList().ToPagedList(page ?? 1, rows);
            TempData["data1"] = data.ToList();
            if (keyword != null)
            {
                if (drp == "username")
                {
                    TempData["data"] = data.Where(x => x.username == keyword || keyword == null || keyword == "").ToList().ToPagedList(page ?? 1, Util.NVLInt(rows));
                    TempData["data1"] = data.Where(x => x.username == keyword || keyword == null || keyword == "").ToList();
                    count = data.Where(x => x.username == keyword || keyword == null || keyword == "").ToList().Count;
                }
                if (drp == "date")
                {
                    TempData["data"] = data.Where(x => x.create_date.Substring(0, 10) == keyword || keyword == null || keyword == "").ToList().ToPagedList(page ?? 1, Util.NVLInt(rows));
                    TempData["data1"] = data.Where(x => x.create_date.Substring(0, 10) == keyword || keyword == null || keyword == "").ToList();
                    count = data.Where(x => x.create_date.Substring(0, 10) == keyword || keyword == null || keyword == "").ToList().Count;
                }
            }
            Session["Search"] = DropdownDao.Instance.GetDrpSearch();
            Session["Count"] = count;
            Session["Rows"] = rows;
            Session["data"] = TempData["data1"];

            ViewBag.Search = Session["Search"];
            ViewBag.Count = Session["Count"];
            ViewBag.Rows = Session["Rows"];

            return View(TempData["data"]);
        }
        public ActionResult ExportToExcel()
        {
            try
            {
                var data = Session["data"] as List<RequestSellListDto>;
                if (data != null)
                {
                    ExcelPackage.LicenseContext = LicenseContext.Commercial;
                    ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                    ExcelPackage Ep = new ExcelPackage();
                    ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
                    Sheet.Cells["A1"].Value = "No.";
                    Sheet.Cells["B1"].Value = "회원아이디";
                    Sheet.Cells["C1"].Value = "이름";
                    Sheet.Cells["D1"].Value = "상품명";
                    //Sheet.Cells["E1"].Value = "개수";
                    Sheet.Cells["E1"].Value = "한개당";
                    Sheet.Cells["F1"].Value = "구매한날짜";
                    int row = 2;
                    foreach (var item in data)
                    {
                        Sheet.Cells[string.Format("A{0}", row)].Value = item.num.ToString();
                        Sheet.Cells[string.Format("B{0}", row)].Value = item.username;
                        Sheet.Cells[string.Format("C{0}", row)].Value = item.fullname;
                        Sheet.Cells[string.Format("D{0}", row)].Value = item.name;
                        //Sheet.Cells[string.Format("E{0}", row)].Value = item.amount;
                        Sheet.Cells[string.Format("E{0}", row)].Value = item.price_interest;
                        Sheet.Cells[string.Format("F{0}", row)].Value = item.create_date;
                        row++;
                    }
                    Sheet.Cells["A:AZ"].AutoFitColumns();
                    Response.Clear();
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment: filename=" + "Report.xlsx");
                    Response.BinaryWrite(Ep.GetAsByteArray());
                    Response.End();


                }
                ViewBag.Search = Session["Search"];
                ViewBag.Count = Session["Count"];
                ViewBag.Rows = Session["Rows"];

                return View("Index");
            }
            catch 
            {
                return RedirectToAction("Index");
            }
        }
    }
}

AHC_DEV_05/AHC_DEV_05/Views/SellHistory/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<AHCBL.Dto.Admin.RequestSellListDto>
@{
    ViewBag.Title = "Sell History";
}
<div class="xp-contentbar" style="margin-top:60px;">
    <div class="row">
        <!-- Start XP Col -->
        <div class="col-md-12 col-lg-12 col-xl-12">
            <div class="card m-b-30">
                <div class="card-header bg-white">
                    <div class="float-left">
                        <h5 class="card-title text-black">상품판매내역 /ประวัติการขาย</h5>
                    </div>
                </div>
                @using (Html.BeginForm("", "SellHistory", FormMethod.Post))
                {
                    <div class="card-body">
                        <div class="justify-content-center row">
                            <div class="col-md-6 col-xl-auto mb-2">
                                @Html.DropDownList("drp", ViewBag.Search as SelectList, new { @class = "bg-white border form-control" })
                            </div>
                            <div id="divKey" class="col-md-6 col-xl-2 mb-2 ml-lg-n4">
                                @Html.TextBox("keyword", ViewBag.CurrentFilter as string, new { @class = "form-control border bg-white" })
                            </div>
                            <div class="col-md-6 col-xl-auto mb-2 ml-lg-n4">
                                <button type="submit" class="btn btn-info mb-2 w-100" id="btnSearchs"><i class="icon-magnifier mr-2"></i>Search</button>
                            </div>

                        </div>
                    </div>
                }

            <div class="card-body mt-lg-n3 table-responsive">
                <div style="min-width:1366px;max-width:100%; margin:auto;">
                    <div class="align-middle">
                        <span class="badge badge-primary badge-pill">전체 @ViewBag.Count 건</span>
                        <div class="float-right">
                            @using (Html.BeginForm("ExportToExcel", "SellHistory", FormMethod.Post))
                            {
                                <button type="submit" id="btnExport" style="margin-top:-10px;" class="btn btn-rounded btn-warning"><i class="icon-printer mr-2"></i> Export</button>
                            }
                        </div>
                    </div>
                    <div class="table-responsive m-b-30 mt-2">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th class="align-middle">No</th>
                                    <th class="align-middle" style="width:200px;">회원아이디 / รหัสสมาชิก</th>
                                    <th class="align-middle">이름 / ชื่อ</th>
                                    @*<th class="align-middle" style="width:150px;">상품명 / ชื่อสินค้า</th>*@
                                    @*<th class="align-middle" style="width:300px;">개수 / จำนวน</th>*@
                                    <th class="align-middle" style="width:300px;">한개당 / ราคาต่อชิ้น</th>
                                    <th class="align-middle" style="width:200px;">구매한날짜 / วันที่ซื้อ</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Count() != 0)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr class="text-center">
                                            <td> @Html.DisplayFor(modelItem => item.num)</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.username)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.fullname)
                                            </td>
                                            @*<td>
                                                @Html.DisplayFor(modelItem => item.name)
                                            </td>*@
                                            @*<td>
                                                @Html.DisplayFor(modelItem => item.amount)<span>개</span>
                                            </td>*@
                                            <td>
                                                @Html.DisplayFor(modelItem => item.price_interest)<span>원</span>
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.create_date)
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr class="text-center">
                                        <td colspan="7">
                                            No Data !!
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    @{
                        if (Convert.ToInt32(ViewBag.Count) > ViewBag.Rows)
                        {
                            <div class="justify-content-center row">

                                @Html.PagedListPager(Model, Page => Url.Action("Index", "SellHistory", new { Page }))

                            </div>
                        }
                    }
                </div>
            </div>
            </div>
            <!-- End XP Col -->
        </div>
    </div>
</div>
<script>
    $(function () {
        $("#liHistory").addClass("active");
        $("#meSellHistory").addClass("active");

    });
</script>