AHC_DEV_05/AHC_DEV_05/Controllers/Admin/MoneyListController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dto.Admin;
using OfficeOpenXml;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.Admin
{
    public class MoneyListController : Controller
    {
        // GET: MoneyList
        Permission checkuser = new Permission();
        // GET: PointList
        public ActionResult Index(int? page, string drp, string keyword)
        {
            checkuser.chkrights("admin");
            var data = PointListDao.Instance.GetDataList(2);
            int rows = Util.NVLInt(Varible.Config.page_rows);
            var count = data.Count;
            ViewBag.Status = DropdownDao.Instance.GetStatusTran();
            TempData["data"] = data.ToList().ToPagedList(page ?? 1, rows);
            TempData["data1"] = data.ToList();
            if (keyword != null)
            {
                if (drp == "username")
                {
                    TempData["data"] = data.Where(x => x.username == keyword || keyword == null || keyword == "").ToList().ToPagedList(page ?? 1, Util.NVLInt(rows));
                    TempData["data1"] = data.Where(x => x.username == keyword || keyword == null || keyword == "").ToList();
                    count = data.Where(x => x.username == keyword || keyword == null || keyword == "").ToList().Count;
                }
                if (drp == "date")
                {
                    TempData["data"] = data.Where(x => x.create_date.Substring(0, 10) == keyword || keyword == null || keyword == "").ToList().ToPagedList(page ?? 1, Util.NVLInt(rows));
                    TempData["data1"] = data.Where(x => x.create_date.Substring(0, 10) == keyword || keyword == null || keyword == "").ToList();
                    count = data.Where(x => x.create_date.Substring(0, 10) == keyword || keyword == null || keyword == "").ToList().Count;
                }
            }
            Session["Search"] = DropdownDao.Instance.GetDrpSearch();
            Session["Count"] = count;
            Session["Rows"] = rows;
            Session["data"] = TempData["data1"];

            ViewBag.Search = Session["Search"];
            ViewBag.Count = Session["Count"];
            ViewBag.Rows = Session["Rows"];

            return View(TempData["data"]);

        }
        public ActionResult Delete(PointListDto model, string[] data)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    foreach (string id in data)
                    {
                        model.id = Util.NVLInt(id);
                        PointListDao.Instance.SaveDataList(model, "del");
                    }
                    return Json("Deleted successfully !");
                }
                else
                {
                    return Json("Data not found !");
                }
            }
            catch (Exception e)
            {
                return Json("Error");
            }
        }
        public ActionResult Updatedata(int id, int status)
        {
            try
            {
                RequestListDto model = new RequestListDto();
                model.id = id;
                model.active = status;
                string result = PointListDao.Instance.SaveDataList(model);
                if (result != "OK")
                {
                    return Json(result);
                }
                else
                {
                    //PointListDao.Instance.SavePoint(id,status);
                    return Json("Successfully !");
                }

            }
            catch (Exception e)
            {
                return Json("Error !!");
            }
        }
        public ActionResult ExportToExcel()
        {
            try
            {
                var data = Session["data"] as List<PointListDto>;
                if (data != null)
                {
                    ExcelPackage.LicenseContext = LicenseContext.Commercial;
                    ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                    ExcelPackage Ep = new ExcelPackage();
                    ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
                    Sheet.Cells["A1"].Value = "회원아이디";
                    Sheet.Cells["B1"].Value = "이름";
                    Sheet.Cells["C1"].Value = "복숭아 내용";
                    Sheet.Cells["D1"].Value = "복숭아";
                    Sheet.Cells["E1"].Value = "일시";
                    Sheet.Cells["F1"].Value = "만료일";
                    Sheet.Cells["G1"].Value = "복숭아합";
                    int row = 2;
                    foreach (var item in data)
                    {
                        Sheet.Cells[string.Format("A{0}", row)].Value = item.username.ToString();
                        Sheet.Cells[string.Format("B{0}", row)].Value = item.fullname.ToString();
                        Sheet.Cells[string.Format("C{0}", row)].Value = item.name.ToString();
                        Sheet.Cells[string.Format("D{0}", row)].Value = item.amount.ToString();
                        Sheet.Cells[string.Format("E{0}", row)].Value = item.create_date.ToString();
                        Sheet.Cells[string.Format("F{0}", row)].Value = item.exp_date.ToString();
                        Sheet.Cells[string.Format("G{0}", row)].Value = item.total.ToString();
                        row++;
                    }
                    Sheet.Cells["A:AZ"].AutoFitColumns();
                    Response.Clear();
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment: filename=" + "Report.xlsx");
                    Response.BinaryWrite(Ep.GetAsByteArray());
                    Response.End();


                }


                ViewBag.Amount = Session["total"];
                ViewBag.Count = Session["count"];
                ViewBag.Search = Session["dropdown"];
                ViewBag.Rows = Util.NVLInt(Varible.Config.page_rows);

                return View("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

AHC_DEV_05/AHC_DEV_05/Views/MoneyList/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<AHCBL.Dto.Admin.PointListDto>
@{
    ViewBag.Title = "충전하기";
}
<div class="xp-contentbar" style="margin-top:60px;">
    <div class="row">
        <!-- Start XP Col -->
        <div class="col-md-12 col-lg-12 col-xl-12">
            <div class="card m-b-30">
                <div class="card-header bg-white">
                    <div class="float-left">
                        <h5 class="card-title text-black">충전하기 / การเติมเงิน</h5>
                    </div>
                </div>
                @using (Html.BeginForm("", "MoneyList", FormMethod.Post))
                {
                    <div class="card-body">
                        <div class="justify-content-center row">
                            <div class="col-md-6 col-xl-auto mb-2">
                                @Html.DropDownList("drp", ViewBag.Search as SelectList, new { @class = "bg-white border form-control" })
                            </div>
                            <div id="divKey" class="col-md-6 col-xl-2 mb-2 ml-lg-n4">
                                @Html.TextBox("keyword", ViewBag.CurrentFilter as string, new { @class = "form-control border bg-white" })
                            </div>
                            <div class="col-md-6 col-xl-auto mb-2 ml-lg-n4">
                                <button type="submit" class="btn btn-info mb-2 w-100" id="btnSearchs"><i class="icon-magnifier mr-2"></i>Search</button>
                            </div>

                        </div>
                    </div>
                }
            <div class="card-body mt-lg-n3 table-responsive">
                <div style="min-width:1366px;max-width:100%; margin:auto;">
                    <div class="align-middle">
                        <span class="badge badge-primary badge-pill">전체 @ViewBag.Count 건</span>
                        <div class="float-right">
                            <button type="button" id="btnDel" style="margin-top:-10px;" class="btn btn-rounded btn-danger"><i class="icon-trash mr-2"></i> Delete</button>
                        </div>
                    </div>
                    <div class="table-responsive m-b-30 mt-2">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th class="align-middle" style="width:50px;"><input type="checkbox" id="checkAll"></th>
                                    <th class="align-middle" style="width:150px;">회원아이디 / รหัสสมาชิก</th>
                                    <th class="align-middle" style="width:200px;">이름 / ชื่อ</th>
                                    @*<th class="align-middle"> 내용/ เนื้อหาพีช</th>*@
                                    <th class="align-middle" style="width:150px;">은행명 / ชื่อธนาคาร</th>
                                    <th class="align-middle" style="width:150px;">예금주 / ชื่อบัญชี</th>
                                    <th class="align-middle" style="width:150px;">계좌번호 / เลขบัญชี</th>
                                    <th class="align-middle" style="width:150px;">수수료 / จำนวนเเต้ม</th>
                                    <th class="align-middle" style="width:170px;">일시 / หยุด</th>
                                    @*<th class="align-middle" style="width:150px;">수수료 합계 / ลูกพีช </th>*@
                                    <th class="align-middle" style="width:150px;">상태 / สถานะ</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Count() != 0)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class=" text-center"> @Html.CheckBox("templateId", new { value = item.id, @class = "checkBox" })</td>
                                            <td>@Html.DisplayFor(modelItem => item.username)</td>
                                            <td> @Html.DisplayFor(modelItem => item.fullname)</td>
                                            @*<td> @Html.DisplayFor(modelItem => item.name)</td>*@
                                            <td class=" text-right"> @Html.DisplayFor(modelItem => item.bank_name)</td>
                                            <td class=" text-right"> @Html.DisplayFor(modelItem => item.acc_name)</td>
                                            <td class=" text-right"> @Html.DisplayFor(modelItem => item.acc_no)</td>
                                            <td class=" text-right"> @Html.DisplayFor(modelItem => item.amount)</td>
                                            <td class=" text-center"> @Html.DisplayFor(modelItem => item.create_date)</td>
                                            @*<td class=" text-right"> @Html.DisplayFor(modelItem => item.total)</td>*@
                                            <td class=" text-right">@Html.DropDownListFor(modelItem => item.status, new SelectList(ViewBag.Status, "Value", "Text", item.status), new { @class = "form-control border bg-white", @onchange = "updatedata(this.value," + item.id + ")" })</td>
                                        </tr>

                                    }
                                }
                                else
                                {
                                    <tr class="text-center">
                                        <td colspan="10">
                                            No Data !!
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    @{
                        if (Convert.ToInt32(ViewBag.Count) > ViewBag.Rows)
                        {
                            <div class="justify-content-center row">

                                @Html.PagedListPager(Model, Page => Url.Action("Index", "MoneyList", new { Page }))

                            </div>
                        }
                    }
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $("#liMember").addClass("active");
        $("#meMoney").addClass("active");
        $("#checkAll").click(function () {
            $(".checkBox").prop('checked',
                $(this).prop('checked'));
        });
        $("#btnDel").click(function () {
            var data = new Array();
            $('input:checkbox.checkBox').each(function () {
                if ($(this).prop('checked')) {
                    data.push($(this).val());
                }
            });
            //alert(selectedIDs); return;
            if (data == null || data == "") {
                alert("Please select at least 1 item.");
                return;
            }
            var options = {};
            options.url = "/MoneyList/Delete";
            options.type = "POST";
            options.data = JSON.stringify(data);
            options.contentType = "application/json";
            options.dataType = "json";
            options.success = function (msg) {
                alert(msg);
                location.reload();
            };
            options.error = function () {
                alert("Error while deleting the records!");
            };
            $.ajax(options);

        });
    });

    function updatedata(val, id) {
        $.ajax({
            type: "POST",
            url: "/MoneyList/updatedata",
            data: "{'id':" + id + ",'status':" + val + "}",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (msg) {
                alert(msg);
                location.reload();
                //location.href = "/Main";
            }
        });
    }
</script>